apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bal-tzar/k8s-assignment
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: todoapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true